// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import '../frb_generated.dart';
import 'error.dart';

part 'product_analytics.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

Future<String> productAnalyticsConsentVersion() =>
    RustLib.instance.api.crateApiProductAnalyticsProductAnalyticsConsentVersion();

Future<ProductAnalyticsSettings> productAnalyticsSettings() =>
    RustLib.instance.api.crateApiProductAnalyticsProductAnalyticsSettings();

Future<ProductAnalyticsSettings> setProductAnalyticsEnabled({
  required bool enabled,
  required String consentVersion,
}) => RustLib.instance.api.crateApiProductAnalyticsSetProductAnalyticsEnabled(
  enabled: enabled,
  consentVersion: consentVersion,
);

Future<ProductAnalyticsTrackStatus> trackProductAnalyticsEvent({
  required ProductAnalyticsEvent event,
}) => RustLib.instance.api.crateApiProductAnalyticsTrackProductAnalyticsEvent(
  event: event,
);

Future<ProductAnalyticsFlushStatus> flushProductAnalytics() =>
    RustLib.instance.api.crateApiProductAnalyticsFlushProductAnalytics();

class AptabaseAnalyticsConfig {
  final String appKey;
  final String host;

  const AptabaseAnalyticsConfig({
    required this.appKey,
    required this.host,
  });

  @override
  int get hashCode => appKey.hashCode ^ host.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AptabaseAnalyticsConfig &&
          runtimeType == other.runtimeType &&
          appKey == other.appKey &&
          host == other.host;
}

@freezed
sealed class ProductAnalyticsBackend with _$ProductAnalyticsBackend {
  const ProductAnalyticsBackend._();

  const factory ProductAnalyticsBackend.disabled() = ProductAnalyticsBackend_Disabled;
  const factory ProductAnalyticsBackend.aptabase({
    required AptabaseAnalyticsConfig config,
  }) = ProductAnalyticsBackend_Aptabase;
}

class ProductAnalyticsConfig {
  final ProductAnalyticsBackend backend;
  final String appVersion;
  final String bundleIdentifier;
  final ProductAnalyticsDeviceClass deviceClass;
  final String osName;
  final String locale;
  final bool isDebug;

  const ProductAnalyticsConfig({
    required this.backend,
    required this.appVersion,
    required this.bundleIdentifier,
    required this.deviceClass,
    required this.osName,
    required this.locale,
    required this.isDebug,
  });

  @override
  int get hashCode =>
      backend.hashCode ^
      appVersion.hashCode ^
      bundleIdentifier.hashCode ^
      deviceClass.hashCode ^
      osName.hashCode ^
      locale.hashCode ^
      isDebug.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProductAnalyticsConfig &&
          runtimeType == other.runtimeType &&
          backend == other.backend &&
          appVersion == other.appVersion &&
          bundleIdentifier == other.bundleIdentifier &&
          deviceClass == other.deviceClass &&
          osName == other.osName &&
          locale == other.locale &&
          isDebug == other.isDebug;
}

enum ProductAnalyticsDeviceClass {
  phone,
  tablet,
  desktop,
  unknown,
}

class ProductAnalyticsEvent {
  final ProductAnalyticsEventName name;
  final List<ProductAnalyticsStringProp> stringProps;
  final List<ProductAnalyticsNumberProp> numberProps;

  const ProductAnalyticsEvent({
    required this.name,
    required this.stringProps,
    required this.numberProps,
  });

  @override
  int get hashCode => name.hashCode ^ stringProps.hashCode ^ numberProps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProductAnalyticsEvent &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          stringProps == other.stringProps &&
          numberProps == other.numberProps;
}

enum ProductAnalyticsEventName {
  analyticsEnabled,
  appStarted,
  appForegrounded,
  appBackgrounded,
  onboardingStarted,
  onboardingCompleted,
  identityCreated,
  loginStarted,
  loginCompleted,
  loginFailed,
  messageSendStarted,
  messageSendCompleted,
  messageSendFailed,
  groupCreateStarted,
  groupCreateCompleted,
  groupCreateFailed,
  membersAdded,
  membersRemoved,
  groupDataUpdated,
  mediaUploadStarted,
  mediaUploadCompleted,
  mediaUploadFailed,
  pushRegistrationCompleted,
  pushRegistrationFailed,
  settingChanged,
}

enum ProductAnalyticsFlushStatus {
  flushed,
  nothingToFlush,
  disabled,
  unconfigured,
  timedOut,
}

class ProductAnalyticsNumberProp {
  final String key;
  final double value;

  const ProductAnalyticsNumberProp({
    required this.key,
    required this.value,
  });

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProductAnalyticsNumberProp &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

class ProductAnalyticsSettings {
  final bool enabled;
  final DateTime createdAt;
  final DateTime updatedAt;
  final String consentVersion;

  const ProductAnalyticsSettings({
    required this.enabled,
    required this.createdAt,
    required this.updatedAt,
    required this.consentVersion,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^ createdAt.hashCode ^ updatedAt.hashCode ^ consentVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProductAnalyticsSettings &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          consentVersion == other.consentVersion;
}

class ProductAnalyticsStringProp {
  final String key;
  final String value;

  const ProductAnalyticsStringProp({
    required this.key,
    required this.value,
  });

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProductAnalyticsStringProp &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

enum ProductAnalyticsTrackStatus {
  queued,
  ignoredDisabled,
  ignoredUnconfigured,
}
