// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Drain all completed Rust spans from the ring buffer.
///
/// Dart calls this every ~1 s while the profiling screen is open and merges the
/// returned events into the shared Perfetto timeline. Safe to call from any thread.
Future<List<RustSpanEvent>> flushRustSpans() =>
    RustLib.instance.api.crateApiProfilingFlushRustSpans();

/// A single completed Rust span, ready for Perfetto JSON serialisation on the Dart side.
class RustSpanEvent {
  final String name;
  final PlatformInt64 startUs;
  final PlatformInt64 endUs;

  /// Thread-id bucket. Values ≥ 100 to avoid colliding with Dart's tid=1.
  final PlatformInt64 tid;

  const RustSpanEvent({
    required this.name,
    required this.startUs,
    required this.endUs,
    required this.tid,
  });

  @override
  int get hashCode =>
      name.hashCode ^ startUs.hashCode ^ endUs.hashCode ^ tid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSpanEvent &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          startUs == other.startUs &&
          endUs == other.endUs &&
          tid == other.tid;
}
