// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import 'error.dart';

// These functions are ignored because they are not marked as `pub`: `configure_default_relay_urls`, `configured_default_relay_urls`, `parse_relay_urls`

Future<List<RelayUrl>> defaultRelayUrlsParsed() =>
    RustLib.instance.api.crateApiRelayDefaultsDefaultRelayUrlsParsed();

List<String> defaultRelayUrls() => RustLib.instance.api.crateApiRelayDefaultsDefaultRelayUrls();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RelayUrl>>
abstract class RelayUrl implements RustOpaqueInterface {}
