// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import 'error.dart';

/// Fetches the latest version string published on Zapstore for White Noise.
///
/// Queries the Zapstore relay for the kind-32267 software application event,
/// then extracts the version from the `a` tag pointing at the latest kind-30063
/// release artifact set (format: `30063:<pubkey>:<identifier>@<version>`).
///
/// Returns `None` when no release has been published yet or the relay is unreachable.
Future<String?> fetchLatestZapstoreVersion() =>
    RustLib.instance.api.crateApiZapstoreFetchLatestZapstoreVersion();
